services:
  # Backend API Service
  - type: web
    name: barbershop-api
    env: python
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn barber_api_production:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barbershop-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: barbershop-db
    databaseName: barbershop
    user: barbershop_user

