services:
  # Backend API Service
  - type: web
    name: barbershop-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn barber_api_production:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: TEST_MODE
        value: true
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        sync: false

databases:
  # PostgreSQL Database
  - name: barbershop-db
    databaseName: barbershop
    user: barbershop_user
    region: oregon
    plan: free
